enum NODE_TYPE {
  TEXT_NODE = 'TEXT_NODE',
  COMMON_NODE = 'COMMON_NODE',
  COMPONENT_NODE = 'COMPONENT_NODE',
}

enum PATCH_TYPE {
  ADD = 'ADD',
  TEXT = 'TEXT',
  PROPS = 'PROPS',
  REPLACE = 'REPLACE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export { NODE_TYPE, PATCH_TYPE };
